# Generated by Django 4.2.7 on 2023-12-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.profile'),
        ),
    ]
