# Generated by Django 4.2.7 on 2023-12-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog.posts'),
        ),
    ]
